version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:5000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5100"
    environment:
      - FLASK_ENV=development
